### ISSUE TITLE
conda installation of 0.3.0 is not working -> "ImportError: No module named cli "

### ISSUE THREAD

**Issue by AHMcKenzie** [ContinuumIO/topik#63] opened 2015-12-01 21:31 UTC
Hi, 
I just installed the 0.3.0 update with conda, however I get an error msg even when executing a simple command-line "help". This is the error:

$ topik --help
Traceback (most recent call last):
  File "/Users/alexmckenzie/anaconda/bin/topik", line 4, in <module>
    from topik.cli import run
ImportError: No module named cli

I'd rather keep using conda and not download the source zip. Thanks for your help
Alex

**Comment by ahmadia** [comment] 2015-12-01 21:33
Thanks, we're looking into it.

**Comment by ahmadia** [comment] 2015-12-01 21:35
reproduced:

```
zsh 14744 [1]  (git)-[master]-% topik --help
Traceback (most recent call last):
  File "/Users/aahmadia/anaconda/envs/python2/bin/topik", line 4, in <module>
    from topik.cli import run
ImportError: No module named cli
```

**Comment by ahmadia** [comment] 2015-12-01 21:38
Looks like this is fixed in master but not in our conda builds.

**Comment by ahmadia** [comment] 2015-12-01 21:47
@AHMcKenzie - as an immediate fix, you can change the text in: 

```
/Users/alexmckenzie/anaconda/bin/topik
```

from:

```
if __name__ == '__main__':
    import sys
    from topik.cli import run

    sys.exit(run())
```

to:

```
if __name__ == '__main__':
    import sys
    from topik.simple_run.cli import run

    sys.exit(run())
```

**Comment by ahmadia** [comment] 2015-12-01 21:48
We've got a bug in our current conda recipe for 0.3.0, we'll rebuild this release as soon as we've got a few minutes.  Thanks for reporting this!

**Comment by ahmadia** [comment] 2015-12-02 05:40
Thanks again for the report @AHMcKenzie

We've released a new build to https://anaconda.org/memex/topik that fixes this issue.  You should be able to just run the install command again to fix it:

```
zsh 15009  (git)-[master]-% conda install -c memex topik
Fetching package metadata: ......
Solving package specifications: .................................................
Package plan for installation in environment /Users/aahmadia/anaconda/envs/python2:

The following NEW packages will be INSTALLED:

    textblob: 0.10.0-py27_0 https://conda.beta.anaconda.org/memex/osx-64/

The following packages will be UPDATED:

    topik:    0.3.0-py27_0 https://conda.beta.anaconda.org/memex/osx-64/ --> 0.3.0-py27_1  https://conda.beta.anaconda.org/memex/osx-64/

Proceed ([y]/n)? y
```

After installation, please check that the `topik` command is running for you.  I'm going to close this issue but please reopen/comment if it's still broken.

**Closed by ahmadia** 2015-12-02 05:40 UTC
Labels: bug
